# /etc/zsh/zshenv: system-wide .zshenv file for zsh(1).
#
# This file is sourced on all invocations of the shell.
# If the -f flag is present or if the NO_RCS option is
# set within this file, all other initialization files
# are skipped.
#
# This file should contain commands to set the command
# search path, plus other important environment variables.
# This file should not contain commands that produce
# output or assume the shell is attached to a tty.
#
# Global Order: zshenv, zprofile, zshrc, zlogin
export USER=$([[ "$(print -P "%#")" == '#' ]] && print 'root' || print 'system')
export HOME=/data/local/${USER}
export ANDROID_ROOT=/system
export ANDROID_DATA=/data
export LC_ALL="C"
export LANGUAGE="C"
export LOGNAME=$USER
export PATH="/system/xbin:/system/bin:/sbin:/vendor/bin:/bin"
export SHELL=zsh
export HISTFILE=${HOME}/.zsh_history
export TERMINFO=/system/usr/share/terminfo
export TERM=xterm-256color
export TMPPREFIX=${HOME}/tmp
